version: "3"

services:
  db:
    image: postgres:14.10
    restart: always
    environment:
      - POSTGRES_USER=tattle
      - POSTGRES_PASSWORD=tattle_pw
      - POSTGRES_DB=uli_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ~/data/uli_test/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db_gui:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api-server:
    container_name: api-server
    build:
      context: api-server
      dockerfile: Dockerfile
    depends_on:
      - db
    # command: tail -f /dev/null
    ports:
      - 3000:3000
    volumes:
      - "./api-server:/app"
      - /app/node_modules
    env_file:
      - "./api-server/development.env"
